version: '3'
services:

  app:
    container_name: wallester_app
    restart: on-failure
    build: .
    ports: 
      - 8080:8080 
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - dbase      
    networks:
      - test-task-nw

  dbase:
    image: postgres:14
    restart: always
    container_name: dbase_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - "5432:5432"
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/0_init.sql
      - dbase_postgres:/var/lib/postgresql/data
    networks:
      - test-task-nw
    
volumes:
  app:
  dbase_postgres:                

# Networks to be created to facilitate communication between containers
networks:
  test-task-nw:
    driver: bridge